### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGWINCH'

### ISSUE THREAD

**Issue by fun840** [bczsalba/pytermgui#1] opened 2021-09-29 01:14 UTC
This module looks really cool, but running the example program (the one from README.md) gives the error,
```
AttributeError: module 'signal' has no attribute 'SIGWINCH'
```
I'm on Windows, which seems like it could be related, but README.md says it supports windows. Any ideas? TIA!

**Comment by fun840** [comment] 2021-09-30 01:23
I did some more googling, and found [this](https://stackoverflow.com/a/10857339/15279203) StackOverflow answer and [this](https://github.com/microsoft/terminal/issues/305) github issue for Windows Terminal, I don't really know anything about the structure of the module but it seems implementable.

**Comment by bczsalba** [comment] 2021-09-30 08:40
Hey! Windows support currently is very hit or miss, there's some quirks of the system I have to get around.

I currently don't have a Windows machine on me, but once I do I'll implement it.

As a note, I'm fairly certain at least one of the example programs is broken since they were written for an essentially different API. Once 1.0.0 is released I will update them and add some more.

Thank you for your interest!

**Comment by bczsalba** [comment] 2021-12-29 10:13
I couldn't figure out an alternative for SIGWINCH on Windows, so for the time being resize events are unhandled on the platform. Thank you for the issue!

**Comment by fun840** [comment] 2021-12-31 14:42
Though I'm not really sure how good of a practice it is, it is (probably) possible to start a thread that runs in the background and checks every 0.01 seconds or something if the window size has changed, then calls `__update_size()`

**Comment by bczsalba** [comment] 2022-01-03 05:33
Yeah, that is definitely something I could do sometime later on. `WindowManager` already runs a separate thread for some actions, so it really shouldn't be that much of a bother.

It also turns out that this issue was not really fixed, according to [this comment](https://www.reddit.com/r/Python/comments/ruligu/comment/hr0wlbe/?utm_source=share&utm_medium=web2x&context=3), but some new commits _should_ have fixed it properly now.

Reopening until I can confirm it was fixed.

**Comment by bczsalba** [comment] 2022-01-07 21:47
So according to #6, this should be fixed now.

**Closed by bczsalba** 2022-01-07 21:47 UTC
Labels: bug
